[project]
name = "quickbeam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "jinja2>=3.1.6",
    "jinjax>=0.48",
    "pydantic-settings>=2.8.1",
    "sqlalchemy>=2.0.39",
]
